export const SUCCESSFUL_REQUEST_STATUS = 200;
export const BAD_REQUEST_STATUS = 400;
export const UNAUTHORIZED_ERROR_STATUS = 401;
export const FORBIDDEN_ERROR_STATUS = 403;
export const NOT_FOUND_STATUS = 404;
export const CONFLICTING_REQUEST_STATUS = 409;
export const INTERNAL_SERVER_ERROR_STATUS = 500;
